monarch-initiative/dipper

dipper/curie_map.yaml

Updating comments fields to better reflect what each ontology refers to and the scope of things it is used for.

Update curie_map.yaml comments

---

dipper/sources/FlyBase.py

Extend flybase from PostgreSQLSource

flybase is postgreSqlSource

---

dipper/sources/FlyBase.py

Small change to check for PMID prefix in flybase literature references, see #267

check for pmid prefix in flybase

---

dipper/curie_map.yaml
dipper/sources/FlyBase.py

1 line change in flybase.py to account for additional field in organism_dbxref view. Also changing curie to point to flybase instead of identifiers.org

Fix organism_dbxref parsing

---

dipper/sources/FlyBase.py
tests/test_flybase.py

Short term fix for cvterm mappings in flybase, will need to implement a better solution moving forward.

Fix cvterm flybase

---

dipper/models/Genotype.py
dipper/sources/FlyBase.py

Removes extra colons in bnodes

Fix bnode generation in Genotype models

---

dipper/sources/ZFIN.py

My intention was to use this branch to fix the zfin gene to phenotype issue, but in the meantime this allows the script to run to completion as it is currently broken.

Fix zfin parser

---

dipper/sources/WormBase.py

Wormbase gene description file is back, include in ingest.

Bring back wormbase gene description

---

dipper/sources/WormBase.py

Reverts monarch-initiative/dipper#326

Revert "Bring back wormbase gene description"

---

dipper/sources/GWASCatalog.py

Fix GWAS parser

---

dipper/sources/ClinVarXML_alpha.py

escape nl in string literal, quote numeric literal

improve represention of literals as ntriples

---

dipper.py
dipper/sources/MGISlim.py
dipper/sources/ZFIN.py
dipper/sources/ZFINSlim.py
dipper/utils/GraphUtils.py
scripts/add-properties2turtle.py

Creates MGI and ZFIN slim files with accurate g2p associations using mousemine and the ZFIN G2P data dump.

MGI and ZFIN clean gene to phenotype assocs

---

dipper/sources/ClinVarXML_alpha.py

handle stray quotes in literals

embedded quotes in string literal

---

dipper/sources/EOM.py

googlegode fix and they added a couple of columns
ref  #268

EOM.py  to pass Jenkins

---

dipper/sources/MMRRC.py

avoid processing variants for withdrawn genes

MMRRC.py to pass jenkins tests

---

dipper/sources/OMIM.py
dipper/sources/Source.py

ignore a couple more lines of header

OMIM.py to pass Jenkins tests

---

dipper/sources/MGI.py

MGI.py  to pass Jenkins tests

---

dipper/sources/Ensembl.py

seeing redirect problems from OHSU network (but not from Eugene)

refactor ensembl url from www to uswest

---

dipper/curie_map.yaml
dipper/sources/ClinVarXML_alpha.py
scripts/ClinVarXML_Subset.sh
scripts/add-properties2turtle.py
scripts/ntriple2dot.awk

address points in #350
add doc
output that the file is an ontology
make all types  rdf:type
allow unexpanded blank nodes
add script to partition clinvar xml test sets from full set and a list of RCVs

unexpand blank nodes

---

scripts/ntriple2dot.awk

addressing issues exposed running over the entire set. Including  
collapsing of purls, alternative blank nodes, the use of "base" nodes,  
and exceptions/alternative  (non-canonical?) uri.

ntriple to dot script

---

dipper/sources/NCBIGene.py

Small fix to remove all omim disease eqs coming from ncbigene.

remove omim disease eqs from ncbigene

---

dipper/models/GenomicFeature.py
dipper/models/assoc/Association.py
dipper/sources/EOM.py
dipper/sources/IMPC.py
dipper/sources/OMIA.py
dipper/utils/DipperUtil.py
scripts/ClinVarXML_Subset.sh
scripts/ntriple2dot.awk

comment change re googlecode in EOM
reflow text in IMPC

IMPC fix taxon link direction

---

dipper/sources/WormBase.py
dipper/sources/ZFIN.py
dipper/utils/DipperUtil.py

- Fix ZFIN pub parser (tsv file has variable number of fields)
- Changes max retries to 10 in requests adapter
- Sets wormbase to use production release (dev release is missing a file)

fixes for flybase, wormbase, and zfin

---

dipper/sources/ClinVarXML_alpha.py
scripts/add-properties2turtle.py

in clinvar:  
made bnodes opaque, gave labels, changed digest to sha1, & formatting
in add-properties2turtle.py :   
change variable name 'format' to   
not conflict with python keyword 'format' and refactored for shorter lines

clinvar blank nodes

---

dipper/sources/WormBase.py

The 'letter' file we derived wormbase's version number from is no longer available.
I switched to an easier method using the CHECKSUMS file 
(which may not have existed before)

wormbase version number fix

---

dipper/sources/ZFIN.py

no zfin pheno env this release

---

dipper/curie_map.yaml
dipper/sources/FlyBase.py
dipper/utils/DipperUtil.py

takes first (big) steps on #380
closes #397 (eutils misuse)

Flybase base nodes and breaking eutils

---

dipper.py
dipper/curie_map.yaml
dipper/models/assoc/Association.py
dipper/sources/Bgee.py
dipper/utils/GraphUtils.py
requirements/all-sources.txt
requirements/bgee.txt

First pass at Bgee ingest as described in https://github.com/monarch-initiative/dipper/issues/147

BGee ingest

---

.travis.yml
README.md
dipper.py
dipper/curie_map.py
dipper/curie_map.yaml
dipper/models/Evidence.py
dipper/models/Provenance.py
dipper/models/assoc/Association.py
dipper/sources/Bgee.py
dipper/sources/IMPC.py
dipper/sources/MyDrug.py
dipper/utils/GraphUtils.py
requirements/all-sources.txt

Ingest of Aeolus data from MyDrug.

MyDrug Aeolus subset data ingest

---

dipper/sources/GeneOntology.py

Fix GOA sources. 

---

Makefile
dipper/graph/RDFGraph.py
dipper/models/GenomicFeature.py
dipper/models/Genotype.py
dipper/models/Model.py
dipper/sources/AnimalQTLdb.py
dipper/sources/GWASCatalog.py
dipper/sources/OMIM.py
dipper/sources/Source.py
dipper/sources/UDP.py
dipper/utils/DipperUtil.py
docs/notebooks/model-api-tutorial.ipynb
scripts/add-properties2turtle.py
tests/test_gwascatalog.py
tests/test_impc.py
tests/test_udp.py

Fixes for the next release:
Other:
closes https://github.com/monarch-initiative/dipper/issues/399, https://github.com/monarch-initiative/dipper/issues/415, https://github.com/monarch-initiative/dipper/issues/386

217 release fixes

---

dipper/models/Model.py
dipper/sources/CTD.py
dipper/sources/KEGG.py
dipper/sources/OMIA.py
dipper/sources/OMIM.py
dipper/sources/Orphanet.py
dipper/sources/WormBase.py
dipper/utils/GraphUtils.py
scripts/add-properties2turtle.py

Annotates variant blank nodes with MONARCH:anonymous annotation property.  Long term the model of anonymous variants to proxy G2P relationships will be removed.

Bnode annotation

---

dipper/sources/ClinVarXML_alpha.py

- change argument language so default behavior is expressed as true  
- wrap one liner digest in a function because it is reused
- force first char of hex digest to be non-numeric. (some non-RDF identifier schemes do not like leading w/digits) 
- avoid printing unhelpful cruft

minor cleanups around bnodes

---

dipper/models/Model.py
dipper/sources/AnimalQTLdb.py
dipper/sources/Bgee.py
dipper/sources/FlyBase.py
dipper/sources/NCBIGene.py
dipper/sources/OMIA.py

Removes labelling of genes, taxa, and making equivalent class axioms in animalqtldb.

Remove taxon labels, equivalentClass axioms

---

dipper/models/Pathway.py
dipper/sources/CTD.py
dipper/sources/Ensembl.py
dipper/sources/KEGG.py
dipper/sources/StringDB.py
tests/test_string.py

Removes explicit P1 - interacts with -> P2, P1 <- interacts with - P2, as this can be inferred at a later point. Fixes ensembl to be compatible with latest release.

Minor updates to string, ensembl

---

dipper/graph/RDFGraph.py
dipper/sources/ClinVarXML_alpha.py
dipper/sources/OMIM.py
dipper/sources/Source.py
dipper/sources/ZFIN.py
dipper/utils/GraphUtils.py
docs/notebooks/clinvar_variant_pathocall_bash.ipynb
scripts/ntriple2dot.awk
translationtable/label_term.tt

- zfin added evidence code to disease file, also un needed carriage return filter was broken 
- omim annual api key update.  runs to completion but noticed many elpty ojects being created . should investigate further
- clinvar have an email in to clinvar inquiring about the xml ""MeasureSet" irems which 
without warning no longer have an "ID" attribute. it will not be hard to adapt but suspect is is a mistake.  other than that i had been making the language around local & global translation tables more consistent 
note clinvar is still expected to fail

ingest maintaince

---

dipper/sources/FlyBase.py
dipper/sources/MGI.py

testing a fllybase fix via Jenkins

flybase test

---

dipper.py
dipper/models/Model.py
dipper/sources/Bgee.py
dipper/sources/Source.py
dipper/sources/StringDB.py

Allows version to be set on the command line for bgee and string.
Note - we should do this for other sources as well.

Allow bgee version to be passed via cmd line

---

dipper/graph/RDFGraph.py
dipper/sources/AnimalQTLdb.py
dipper/sources/ClinVarXML_alpha.py
dipper/sources/FlyBase.py

lets not talk about it too much

beating fly into submission

---

Makefile
dipper/sources/Ensembl.py
dipper/sources/StringDB.py
tests/test_string.py

- Type uniprot proteins
- upfront map proteins to genes
- use try/except instead of searching keys in large dictionary
https://github.com/monarch-initiative/dipper/issues/444#issuecomment-306870845

use try/except instead of searching large dict

---

dipper/sources/MGI.py
dipper/sources/PostgreSQLSource.py
resources/sql/all_allele_mutation_view.sql
resources/sql/all_allele_view.sql
resources/sql/all_summary_view.sql
resources/sql/bib_acc_view.sql
resources/sql/gxd_allelepair_view.sql
resources/sql/gxd_genotype_summary_view.sql
resources/sql/gxd_genotype_view.sql
resources/sql/mgi_dbinfo.sql
resources/sql/mgi_note_allele_view.sql
resources/sql/mgi_note_vocevidence_view.sql
resources/sql/mrk_acc_view.sql
resources/sql/mrk_location_cache.sql
resources/sql/mrk_marker_view.sql
resources/sql/mrk_summary_view.sql
resources/sql/prb_strain_acc_view.sql
resources/sql/prb_strain_genotype_view.sql
resources/sql/prb_strain_view.sql
resources/sql/voc_annot_view.sql
resources/sql/voc_evidence_view.sql
tests/omia-integration.py

- Replaces Select * queries
- Parses correct rows in voc_annot_view to pull in model of relationships
- Adds OMIA integration test (OMIA ingest pulls from three sources)
- Bug fix when mapping alleles to markers
Fixes #491

Fix for missing model_of relationships from DO switch

---

dipper/sources/GWASCatalog.py

remove spaces in "id"  (it is not an id)
re shape  narrower

gwas catalog variant_id fix

---

dipper/models/assoc/Association.py
dipper/sources/Ensembl.py
dipper/sources/NCBIGene.py
dipper/sources/Source.py
dipper/sources/StringDB.py
dipper/sources/ZFIN.py
resources/clique_leader.yaml
scripts/string/id-map-conf.yaml
scripts/string/map-string-ids.py
scripts/string/requirements.txt
tests/test_gwascatalog.py
tests/test_impc.py
tests/test_string.py

- Taxa specific ID spaces as clique leaders: fixes #466 
- String confidence cutoff: fixes #484
- String mapping deprecated ENSP to genes: see #481
- ZFIN and MGI equivalence bugs: fixes #505
- Ensembl gene to uniprot map: fixes #461

Fixes for August release

---

dipper/sources/ClinVarXML_alpha.py
dipper/sources/Source.py
translationtable/facebase_alpha.tt

- starts identifiers with non digit
- comment and fix line endings on (unused) translation table

minor update

---

tests/test_gwascatalog.py
tests/test_impc.py

Adds 'b' at beginning of bnodes in tests.

fix tests for new identifier pattern

---

dipper/sources/Panther.py

account for curies with multiple colons

panther fix

---

dipper/sources/ClinVarXML_alpha.py

None guard resolving scv_evidence_type

clinvar fix

---

dipper/sources/Panther.py
dipper/sources/WormBase.py
scripts/ntriple2dot.awk

- ntriple2dot.awk remove hardcoded mappings from crusty days of yore 
- WormBase.py xref file is gone. have email to michael.paulini at wormbase.org

WormBase adjustment

---

dipper-etl.py
dipper/curie_map.py
dipper/curie_map.yaml
dipper/sources/OMIM.py
dipper/utils/CurieUtil.py

- main thing I want to use right away is the curie map with more uniform whitespace
- removed  out of date comments
- remove broken code that dosen't seem needed anymore

mostly cleanup

---

dipper/sources/GWASCatalog.py
tests/test_gwascatalog.py

Updates for new MONDO release that includes EFO diseases.  Some hackery since MONDO uses the prefix http://purl.obolibrary.org/obo/EFO_ and EFO uses http://www.ebi.ac.uk/efo/EFO_

update for compatibility with MONDO release

---

Makefile
dipper-etl.py
dipper/curie_map.yaml
dipper/sources/SGD.py
tests/test_sgd.py

Sacchromyces Genome Datbase Gene 2 Phenotype Associations

Sgd phenotypes

---

dipper/sources/Ensembl.py
dipper/sources/HGNC.py
dipper/sources/NCBIGene.py
dipper/utils/DipperUtil.py
resources/impc_mappings.yaml
scripts/README.md

Update IMPC mappings, adjusts xref vs eq axioms for human genes

IMPC fix, gene eqs

---

dipper/curie_map.yaml
dipper/sources/BioGrid.py
dipper/sources/GWASCatalog.py

GWASCatalog add new column

---

Makefile
dipper/models/Evidence.py
dipper/models/Model.py
dipper/sources/IMPC.py
dipper/sources/MGI.py
resources/sql/mgi/evidence.sql
resources/sql/mgi/voc_evidence_view.sql
tests/resources/mgi/evidence_view
tests/test_mgi.py
translationtable/global_terms.yaml

Aligns IMPC with MGI model for qualifying sex when applicable.  Technically redundant with the geno model which captures sex specific genotypes.

WIP: Align Impc sex specificity with MGI

---

dipper/sources/EOM.py

I was starting to shorten line but  ... ooo shiny!

restore url

---

dipper/sources/MMRRC.py

seems we loaded padded keys and retrieved stripped keys and it bit us

fix inserting padded keys

---

dipper/curie_map.yaml
dipper/sources/AnimalQTLdb.py
dipper/sources/Source.py

- Animal QTL
- break out the curie/url for each species
- dataset changes per last PR
- Source.py  
- Have the ingest super class Source house the global and local translation tables 
- include a function to resolve keys

AnimalQTL fix and translation tables in Source.py

---

dipper/sources/Coriell.py
dipper/sources/MMRRC.py
dipper/sources/ZFIN.py

_alternate_ to _variant_  #610 follow up

---

dipper/sources/Coriell.py
dipper/sources/MGI.py
dipper/sources/MMRRC.py
dipper/sources/ZFIN.py

next one might be the other way around

underscore to spaces

---

dipper/models/Family.py
dipper/models/Model.py
dipper/models/assoc/Association.py
dipper/sources/BioGrid.py
dipper/sources/Coriell.py
dipper/sources/EOM.py
dipper/sources/FlyBase.py
translationtable/flybase.yaml
translationtable/global_terms.yaml
translationtable/omim.yaml

- remove left over early tt plumbing
- remove no longer used mappings
- fix typo in omim tt

cut dead code, typos, use resolve

---

Pipfile
dipper/sources/GeneOntology.py
dipper/sources/HPOAnnotations.py
dipper/sources/OMIM.py
translationtable/hpoa.yaml

nothing earthshaking
hpoa gitpython will come back to bite me unless I bite it first

more of the same  #610 follow up

---

dipper/models/assoc/OrthologyAssoc.py
dipper/sources/GeneOntology.py
dipper/sources/MGI.py
dipper/sources/NCBIGene.py
dipper/sources/OMIA.py
dipper/sources/OMIM.py
dipper/sources/OrthoXML.py
dipper/sources/Panther.py
translationtable/global_terms.yaml
translationtable/mgi.yaml
translationtable/panther.yaml
translationtable/ucscbands.yaml

don't mind me, still whacking the occasional mole
added panther terms

winnowing jenkin's error reports III

---

dipper/models/Genotype.py
dipper/sources/CTD.py
dipper/sources/ClinVarXML_alpha.py
dipper/sources/FlyBase.py
dipper/sources/GeneOntology.py
dipper/sources/GeneReviews.py
dipper/sources/HGNC.py
dipper/sources/MGI.py
dipper/sources/MMRRC.py
dipper/sources/OMIA.py
dipper/sources/OMIM.py
dipper/sources/Source.py
dipper/sources/UCSCBands.py
dipper/sources/ZFIN.py
translationtable/clinvarxml_alpha.yaml
translationtable/global_terms.yaml
translationtable/hgnc.yaml
translationtable/mgi.yaml
translationtable/omim.yaml

Another pass at the issues that pop up in Jenkins  
and a pass at making Clinvar 1) run 2) be more consistent with other ingests

winnowing jenkin's error reports 4 & ClinVar 

---

dipper/models/assoc/OrthologyAssoc.py
dipper/sources/GeneOntology.py
dipper/sources/HGNC.py
dipper/sources/HPOAnnotations.py
dipper/sources/MGI.py
dipper/sources/OMIM.py
dipper/sources/OrthoXML.py
dipper/sources/Panther.py
dipper/sources/UCSCBands.py
translationtable/hgnc.yaml
translationtable/panther.yaml

more of the same, just have to look harder

winnowing jenkin's error reports V

---

dipper/models/assoc/OrthologyAssoc.py
dipper/sources/OMIM.py
dipper/sources/UCSCBands.py
translationtable/hgnc.yaml
translationtable/panther.yaml

more of the same, just have to look harder

winnowing jenkin's error reports VI

---

dipper/models/Genotype.py
dipper/sources/MGI.py
dipper/sources/Panther.py
dipper/sources/UCSCBands.py
translationtable/omia.yaml

winnowing jenkin's error reports VII

---

dipper/models/Genotype.py
dipper/sources/MGI.py
dipper/sources/UCSCBands.py
translationtable/mgi.yaml

must be time to stop , I thought these were in already

Redo?  last pull

---

dipper/sources/UCSCBands.py

minor fix, trailing comma on lists

UCSC bands 

---

translationtable/mgi.yaml

added an `S`  on a local MGI tt key

suspect a sloppy save

---

dipper/sources/GeneOntology.py

make test_ids exist in self

---

dipper/sources/GeneOntology.py

indentation

---

dipper/sources/GeneOntology.py

instead of once per taxon processed

Build uniprot id_map once

---

dipper/sources/GeneOntology.py

it makes a new object for each taxon ingest so 
we don't get to keep work between taxon there.
So here we write  the expensive to generate map out as a yaml file 
and read the cheap results back for reuse if they are not stale.

write/read yaml cache of UniProt mappings

---

dipper/sources/GeneOntology.py

yaml dumps

---

Pipfile
dipper/sources/GeneReviews.py
dipper/sources/OMIA.py

yes duplicated code is bad but for now I will take it over dependency
will eventually extract common function and make callable from any ingest

GeneReviews gets  it's omim_type same as OMIA

---

dipper/sources/HPOAnnotations.py

Use common-diseases-mondo

---

translationtable/GLOBAL_TERMS.yaml

Coriell got its model_of  back

missing comma

---

dipper/sources/HPOAnnotations.py

term label matching

---

dipper/sources/GeneOntology.py
dipper/sources/Panther.py

drop a couple of now unused imports

Panther, cast txid nums to strings

---

dipper/sources/Panther.py

add none guard

---

dipper/sources/GeneReviews.py

- use table header sent to monitor for change 
- use builtin line count
- regex compile out of loop body (question the use for static constant pattern match)
- replace single char vars with more descriptive nanes 
- more logging on what file is being processed and header conditions

Genereviews fixes 

---

dipper/curie_map.yaml
dipper/sources/Ensembl.py
dipper/sources/HGNC.py
dipper/sources/MGI.py
dipper/sources/MPD.py
dipper/sources/Monochrom.py
dipper/sources/Orphanet.py
dipper/sources/ZFIN.py
tests/test_ensembl.py

- typos, missing/extra chars
- wrong op for type
- point to new loc for test ids

fix tiny errors

---

dipper/models/Model.py
dipper/models/Reference.py
dipper/models/assoc/Association.py
dipper/sources/EBIGene2Phen.py

neither curie nor IRI  as source are literals

---

Makefile
dipper/graph/Graph.py
dipper/graph/RDFGraph.py
dipper/sources/BioGrid.py
dipper/sources/Reactome.py
dipper/sources/Source.py
tests/test_biogrid.py
tests/test_source.py

- global effects in how curies are recognized (more lenient)
- global change in test id availability in unit tests (exist now)
- file sizes are now zero when they were None or empty
- Biogrid included in Makefile unit test suite

Biogrid & Reactome test passing

---

dipper/sources/NCBIGene.py
dipper/sources/OMIA.py

process all the omia files the same way  (only one was parsed as csv)
needed to remember to split the string csv had been splitting.
getting the source xml parsing row-line  consistent likely helped as well.
and there is always more logging and comments .
I expect travis will have another network timeout on impc about now

OMIA (& NCBI) working

---

dipper/sources/OMIA.py
tests/omia-integration.py

integration test has hardcoded IRI which fail when curie_map changes

OMIA test fix

---

dipper/curie_map.yaml

should have been included in previous PR

curie_map update

---

dipper/sources/Monarch.py

Expected headers introduced & used in Monarch.py
movement towards common conventions across ingests

remove stray debugging stmt

---

Jenkinsfile

Jenkins declarative pipeline file for dipper that fetches and parses sources and adds rdf files to data.monarch.  Also runs the monarch-merged owl job.

Add jenkins pipeline for dipper

---

Jenkinsfile
dipper/sources/GeneReviews.py
translationtable/panther.yaml

first go at modifying Jenkins dipper-pipeline
- new mapping for Panther to cats
- fix unfinished name change
- note most of the Jenkins changes are automatic white space trimming

OMIM PR supplement

---

dipper/sources/GWASCatalog.py
dipper/sources/IMPC.py
dipper/sources/Panther.py
tests/test_impc.py
translationtable/GLOBAL_TERMS.yaml
translationtable/panther.yaml

- Panther changed a species abbrev for dog which is fixed in the translation tables
- IMPC got a new test which had not fully propagated which is fixed with a import or so, (thanks Justin)
Since the ingests got touched (well nearly anyway) 
I did what has become a standard refactor
where 'pylint' & 'pytype' complaints are reduced, 
file headers are more thoroughly checked   
and a number of little conventions are migrated towards

Panther & IMPC fixes

---

dipper/sources/Bgee.py
translationtable/GLOBAL_TERMS.yaml

- updated translation tables
- made bgee a bit less dependend on its own taxon mapping
checked that bgee runs but can't test coriell from home right now (ssh keys)

Coriell and BGEE broke on dog changing to include lupus

---

dipper/sources/GWASCatalog.py
dipper/sources/GeneReviews.py
dipper/sources/HGNC.py
dipper/sources/OMIA.py
dipper/sources/OMIMSource.py
dipper/sources/SGD.py
translationtable/GLOBAL_TERMS.yaml
translationtable/flybase.yaml

update UPHENO:0001001 term label to agree with ontobee
will merge tomorrow without objections

Phenotype -> phenotype

---

dipper/sources/GeneOntology.py

Fixed minor logical issue (to do with string/int comparisons in self.tax_ids) that was preventing GO annotation ingest from producing TTL

Fix tax ids issue in go ingest

---

dipper/sources/GeneOntology.py

fix broken tests, broken when tax_ids is None

fix_bug_in_assigning_tax_ids

---

dipper/sources/GeneOntology.py

to speed things up, moved call to ZFIN() and WormBase() to constructor instead of in process_gaf(), so it gets called once per GeneOntology instance, instead of once per invocation of process_gaf() (which gets called a lot). Saves a lot of time. 
out.ttl produced by this commit is exactly the same as [current HEAD of Dipper master branch](https://github.com/monarch-initiative/dipper/tree/809eaed30c60ec217854d6f384be638627d5b0d9), so I am convinced this isn't harmful:
md5 hash of out/go.ttl produced by [this PR](https://github.com/justaddcoffee/dipper/tree/c23870467a4cf50739e53c09516087631f78985e)
`MD5 (/Users/jtr4v/projects/MI/dipper/dipper-justaddcoffee-fork/out/go.ttl) = e6527af8e4bca9f11b2be3c82e660a14`
md5 hash of out/go.ttl produced by [current HEAD of master branch of main Dipper …

speed up GO annotation ingest by moving calls to ZFIN() and WormBase()

---

dipper/utils/GraphUtils.py
tests/resources/graphutils/gu_test_graph.ttl
tests/resources/graphutils/gu_test_graph2.ttl
tests/test_graph_utils.py

needed this for two things at the moment, so thought it might be generally useful

added simple method to compare counts of predicates between two graphs

---

dipper-etl.py
dipper/curie_map.yaml
dipper/sources/GeneOntology.py

addresses #766 
refactor column headers etc
add s couple of new species types(mould & fungi)
bump date for monarch archive
change  
'<gene> <has_synonym> "prot_curie" .'
to    
'<gene> <same _as> <prot_curie> .'
(open to alternative associations)

Go annotation

---

Jenkinsfile
dipper/curie_map.yaml

Jenkins pipeline
- Build dipper once
- Move files in single step
- Add ucscbands and omia
Curie map:
- Add gard, cohd, sctid, icd9

DRY out jenkins pipeline; add gard, cohd etc to curie map

---

dipper/sources/ClinVarXML_alpha.py

Linting
- lines longer than 88
- wrong number of blank lines
Guard against emitting `None`  as a disease label 
Started as an exercise to remove errant intermediate file
but the file only still existed due to the previous error.

Clinvar assert RDF object is not None

---

Makefile
dipper/sources/Monochrom.py
dipper/sources/OMIM.py
dipper/sources/UCSCBands.py

indel s in phenotypic series url

OMIM, Monochrom/UCSCBands

---

.travis.yml
Jenkinsfile
Makefile

remove python 3.5 from travis, specify 3.6 in jenkinsfile

remove python 3.5 from travis, specify 3.6 in jenkinsfile

---

dipper/curie_map.yaml
dipper/sources/HGNC.py
scripts/ntriple2dot.awk

cleaning up IRI for dot qc checks
it is nice to see old exceptions in ntriples2dot go away

Post process IRI sweep

---

dipper/models/Genotype.py

thought this add was committed in my last PR

include forgotten commit

---

dipper/sources/Ensembl.py
dipper/sources/StringDB.py

Move list creation for dict values from Ensembl  (where no list are seen yet)
to String where lists are appropriate for consistency with other conditions.
Ensembl: Write out intermediate input from query so we can know and record what we got.
(should likely do more of this as opportunity allows) 
String; refactor dict values update to be more pythonic

String Ensembl

---

dipper-etl.py
dipper/sources/Ensembl.py
dipper/sources/Source.py
dipper/sources/StringDB.py

and normal refactoring of dubious stuff

Stringdb delay for fetch

---

dipper-etl.py

remove taxa default arg, add ensembl to supported

remove taxa default arg, add ensembl to supported

---

Pipfile
dipper/sources/Decipher.py
dipper/sources/HGNC.py
dipper/sources/NCBIGene.py
dipper/sources/OMIA.py
dipper/sources/Panther.py
translationtable/GLOBAL_TERMS.yaml

- ncbigene: corrects a logging error
- panther: uses a newly added curie
- avoids passing necessary var
- generalizes  stuttered curie-prefix repair
- omia: moves an object creation into init() so it happens once
- (not convinced current logical process here is optimal, but this is not worse)  
- added hgnc comment
- commented out won't fix lines in decipher (which is on it's way out)

small fixes

---

dipper/sources/OMIM.py

USER_AGENT doesn't exist in OMIM.py, I think this is supposed to be imported from OMIMSource

fix broken import in OMIM.py

---

Makefile
dipper/sources/HGNC.py

About  4% of the HGNC records are withdrawn
here I am avoiding propagating them without warning.
the set of non-approved records (and symbols) is collected 
in hopes we will vet other ingests use of HGNC identifiers for obsolete associations.

HGNC filter withdrawn enteries

---

.travis.yml

enable more default test coverage

travis tests

---

dipper/sources/OMIM.py

lint on Jenkins reports an error I do not see when running it locally and that Travis also passes over.

Jenkins lint error

---

dipper/models/Genotype.py

Lint on jenkins is doing a better job than on travis or localy

Jenkins lint find

---

dipper/sources/NCBIGene.py

Curie v.s. omim number mismatch
adds 16,076 omim dbxref

NCBIGene fix omim dbxref

---

dipper/sources/ClinVar.py
dipper/sources/IMPC.py
translationtable/GLOBAL_TERMS.yaml

simple update, no apparent regressions

update term label to match OLS

---

dipper/sources/IMPC.py

Pull latest directory from IMPC

Pull latest from IMPC

---

dipper/sources/OMIMSource.py

Column name changed from 'Mim Number' to 'MIM Number'
Makefile is broken on Mac, no idea if this passes unit tests

Fix for OMIM ingest

---

dipper/sources/HGNC.py
dipper/sources/Monarch.py
dipper/sources/NCBIGene.py
dipper/sources/RGD.py
dipper/sources/SGD.py
dipper/sources/WormBase.py

Touched allot of dipper files recently while focusing on other things
this PR is just minor refactors linting & comments so they wont get mixed in with 
more meaningful changes.

Minor misc clearing the decks

---

dipper/sources/Source.py

missed last line block indenting

fix mis indented

---

dipper/sources/Panther.py

Jenkinsfile Clinvar path

---

dipper/sources/FlyBase.py

fixes for fly flat file fetching
changed regexs  to also recognise renamed file
make the paths more explicit
try reverting to cache on failure to fetch instead of hard fail

Flybase: refactor file fetching (due to missing file)

---

dipper/sources/Source.py

For source files retrieved from DipperCache, currently we are missing metadata such as: 
```
<http://purl.obolibrary.org/obo/zp//id_map_zfin.tsv> pav:retrievedOn "2019-12-02T09:38:46"^^xsd:dateTime .
```
and: 
```
<https://archive.monarchinitiative.org/20200109/#zfin> 
dcterms:source
<https://archive.monarchinitiative.org/DipperCache/zfin/id_map_zfin.tsv>,
```

Fix metadata (dct:source and pav:retrieved_on) for files retrieved from DipperCache

---

Jenkinsfile

fix missing comma in taxon list

---

Jenkinsfile

the date stamp generation needs to be wrapped in a groovy function

Groovy can call the shell but it is not the shell

---

Jenkinsfile
dipper-etl.py
dipper/sources/GeneOntology.py
dipper/sources/HPOAnnotations.py
dipper/sources/Monochrom.py
dipper/sources/NCBIGene.py

another incremental improvement on our pipeline process

Pipeline polish push

---

Jenkinsfile

used the wrong style comment char for groovy . needs:   
C++/Java style line comment `//` 
instead of perl/python/shell style line comment `#`

Jenkins file comment char

---

Jenkinsfile

you get to see what could go wrong

Learning groovy (Jekins pipeline)  without a test env 

---

dipper/sources/IMPC.py

there may be more but starting with this.

IMPC: refactor to reduce uninformative logging

---

Jenkinsfile
dipper/sources/MGI.py
dipper/sources/Source.py
scripts/mdma.sh
tests/resources/mgi/evidence_view

Put column checking on all fetched tables
add `src_key` parameter to help know which file a column log report is for
Untested  dipper-pipeline Jenkinsfile changes
- try adding a Jenkinsfile lint/validator stage 
- shorten  lines & labels
- add final bulk move stage if all previous stages passed
- experiment with tagging dipper repo as a reference for the release

MGI refactor for conventions

---

Jenkinsfile

- have monochrom use blank nodes for ontology building
- comment out animalqtl (till we resolve their file fetching)

Jenkinsfile minor edits

---

dipper/sources/OMIM.py

refinement on slowing down api calls

OMIM api backoff

---

dipper/sources/HGNC.py

- fix passing empty string as pubmed_id;
- include new trailing column header 'agr'

HGNC add  default hgnc gene 'in taxon'

---

dipper/sources/HGNC.py
dipper/sources/MPD.py
resources/zfin/README

no significant changes in output expected

MPD standard refactor

---

dipper/sources/Orphanet.py

the rest of the changes is just out-denting from negating the inclusion criteria and continuing
they might not be done remuddeling their model, will have to recheck it

change OrphaNumber to OrphaCode

---

Jenkinsfile

Jenkinsfile lowercase 'Stage'

---

Jenkinsfile
dipper/models/Genotype.py
dipper/sources/Coriell.py
dipper/sources/EOM.py
dipper/sources/MGI.py
dipper/sources/UCSCBands.py

Final dipper pipeline stage is given a moments pause for the file-system to quiet down to addresses the data transfer script getting off to a false start.   
Also begin looking into moving the final stage to the Jenkins pipeline builtin stage  named "post".  
- correct ancient comments misusing the `rdf:` & `rdfs:` name spaces
- correct a couple of code indents

Jenkinsfile  & misc comment

---

dipper/sources/NCBIGene.py
dipper/sources/OMIMSource.py
dipper/sources/Orphanet.py
dipper/sources/Source.py
scripts/mdma.sh
tests/test_source.py

- addresses #961
- restore default taxon in more general form. 
- (no recollection of why I commented them out months ago)
- write out the omim dicts for type & replacement status
- repair incidental test breakage  from category branch
- begin sorting and de-duping ntriples earlier rather than later

NCBI  OMIM disease as gene fix

---

Jenkinsfile
dipper/sources/KEGG.py
dipper/sources/OMIA.py

KEGG 
-  synchronize filenames between the ingest and DipperCache
- note that many are ignored after fetching see:
- https://github.com/monarch-initiative/dipper/issues/141
- drop files and code we decided not to use 5 years ago.
OMIA:
- URL-encode un-resovable  LIDA uri
(recent crack down URI which were expressed as literals forces hand.)
Commented MyChem out of the Jenkinsfile  as it being non-functional 
is not an error

KEGG refactor & OMIA fix

---

dipper/models/Pathway.py
dipper/sources/Ensembl.py

Same as previous PR but for dipper.models.Pathways.
Try changing the Ensembl mart fetch back to uswest 
as the one on the other side of the pond is having issues again.

Adendum II to PR #982 (Digest bnode ids & refactor) 

---

dipper/models/Genotype.py
dipper/sources/Coriell.py
dipper/sources/IMPC.py
dipper/sources/MPD.py
dipper/sources/UDP.py
dipper/sources/ZFIN.py
translationtable/GLOBAL_TERMS.yaml
translationtable/impc.yaml
translationtable/mgi.yaml

update tems&labels, add a new mouse 

---

dipper/sources/AnimalQTLdb.py
resources/wormbase/README_ftp_202009
resources/wormbase/letter.WS277
translationtable/animalqtldb.yaml

they moved to newer assemblies 
basic refactors
include some wormbase artifacts for reference 
to help next time they change something

AnimalQTL updates

---

scripts/deltadot.awk

correct color for reduced count, 
mistakenly made it 'drop edge' color 
when I added the legend

dot-qc color change

---

dipper/sources/GeneReviews.py
dipper/sources/KEGG.py
dipper/sources/MGI.py
dipper/sources/MyChem.py
dipper/sources/OMIA.py
dipper/sources/UDP.py
resources/omia/README_casual_mutation
tests/test_mychem.py
tests/test_udp.py
translationtable/GLOBAL_TERMS.yaml
translationtable/omia.yaml

At this point any DOIDs in dipper output 
are passed through from the source.
addressed #998

DOID -> MONDO 

---

Jenkinsfile
dipper-etl.py
dipper/curie_map.yaml
dipper/sources/Xenbase.py
translationtable/rgd.yaml
translationtable/xenbase.yaml

A prototype xenbase ingest for G2P and gene to literature associations
For the koza version see https://github.com/monarch-initiative/koza/pull/8

xenbase prototype
