monarch-initiative/dipper

dipper/curie_map.yaml

The UniProt purls resolve to www.uniprot.org if html is requested but if the user wants RDF they get RDF. Using UniProt purls makes cross querying between sparql.uniprot.org and other data sources easier.

Use UniProt purl's for UniProt data

---

dipper/curie_map.yaml

Reverts monarch-initiative/dipper#300
This has some implications downstream, specifically in how SciGraph resolves IRI's to curies.  The issue here is having three curie prefixes with the same IRI prefix mapping.  This breaks the scigraph-services, essentially both keys and values need to be unique sets.
Could we alternatively have a single curie prefix that maps to http://purl.uniprot.org/uniprot/ ?

Revert "Use UniProt purl's for UniProt data"

---

dipper/sources/FlyBase.py

Changes property from equivalentClass/sameAs to OIO:hasDbXref, as this was causing equivalences between fly and human genes.

change equivalent/sameAs to xref when processing dbxref table

---

dipper/sources/AnimalQTLdb.py

ingest was finding rsid where it thought it had p-value score
made ignore all non numeric p-value scores 
(which does not address how or where the wrong  thing happens)
also at least one gene name is given where the id/symbol should be
fixed the particular case and preventing accepting spaces in future gene id/symbols

AnimalQTLdb.py  to pass Jenkins tests

---

dipper/utils/GraphUtils.py

Boolean in dipper output currently look like `<http://www.ncbi.nlm.nih.gov/pubmed/11566854> :MONARCH_cliqueLeader "true"^^xsd: .` The python code was calling `XSD[bool]`, which works for some reason and just returns the namespace URI. Changed to `XSD['boolean']` so that the correct URI will be output as `xsd:boolean`.

Fixed bug in XSD:boolean URI

---

dipper.py
dipper/graph/RDFGraph.py
dipper/graph/StreamedGraph.py
dipper/models/assoc/Association.py
tests/test_ctd.py
tests/test_gwascatalog.py
tests/test_impc.py
tests/test_reactome.py

Change 
http://purl.org/oban/association_has_object_property
to
http://purl.org/oban/association_has_predicate
Skolemize bnodes by default
Closes https://github.com/monarch-initiative/dipper/issues/278, https://github.com/monarch-initiative/dipper/issues/380

Change OBAN relation, skolemize bnodes by default

---

dipper/sources/HPOAnnotations.py

We should never use github URLs for ontologies, and never the editors version, always use a PURL of the release version

Use correct purl for DOID

---

dipper/sources/GWASCatalog.py

removes spaces and changed ```-?``` to ```-N``` where we now create bogus IRI.
consider replacing base:404 with bnode with label

gwas catalog broken iri fix

---

dipper/sources/FlyBase.py
dipper/sources/MGI.py

- flybase moved their read only postgresql instance to a machine named `chado`
- unannounced, found by looking for pages with recent edits in their wiki
- in MGI guard against stray tabs in TSV by skipping rows with the wrong number of columns
- tabs are not invalid in the database and are not escaped when selected out
- we were producing blank nodes with double colons  `_::yadayamgibackground`
Have a ticket in to mgi to address the specific case we are working around
suggest they trim leading/trailing whitespace of freetext on ingest.
Flybase is not completing because a FBgnID worms (flutters?) into dbxref and we do not supply a curie for it.    
note Flybase is not sending the FBgn in their dbxref dataset we are doing this ourselves.

mgi running and  host change for fly 

---

dipper/sources/MGI.py

One of the many consequences of getting data from someone else's  database with  
```SELECT * FROM table;```   
is when they drop a column that we do not use, it breaks our code.

they dropped the 'markersymbol' column from all_allele_view table

---

dipper/sources/Panther.py
dipper/sources/Source.py
dipper/utils/CurieUtil.py

because blacklisting requires ongoing maintenance with a very long test cycle

use curie map to whitelist panther prefixes

---

dipper/models/Dataset.py

* This patch is made to solve the issue posted at https://github.com/monarch-initiative/dipper/issues/525. 
* I was testing Blazegraph triplestores with ttl files in the data repository (https://data.monarchinitiative.org/ttl) and found that Blazegraph's parser did not allow importing some *_dataset.ttl files because object values of dct:issued did not conform xsd:dateTime format, i.e. 2017-09-25-09-00 should be 2017-09-25T09:00:00. I tracked the codes and found that the value was generated by line 35 in Dataset.py (https://github.com/monarch-initiative/dipper/blob/master/dipper/models/Dataset.py). I fixed the format of the date to conform the xsd:dataTime format so that ttl filescan be imported without errors.

Modify the format of date_accessed value to conform xsd:dateTime format.

---

dipper-etl.py
dipper/sources/Source.py
dipper/sources/WormBase.py
tests/test_source.py

- wormbase played hide the xref file
- extend the RDF formats  data files may be output as
- now includes nquads
- ensure `_dataaet` and `_test` files are only written as turtle 
- reduce the usage of python keywords as user variables i.e `format`
- make http headers have RCF specified case (I believe lib took care of it anyway)
- corrected string representation of number that likely tainted file size comparisons

restore WB xref; output RDF formats; var keyword abatment; remote file change detection 

---

dipper/sources/FlyBase.py
dipper/sources/HPOAnnotations.py
dipper/sources/MMRRC.py
resources/sql/fb/stockprop.sql
scripts/treeify-hpo.py
tests/test_flybase.py
tests/test_gwascatalog.py
tests/test_udp.py

- Removed primary key reference for cvterm, replaces with join and matching on cvterm label
- Adjustment for 15th column in hpoa, note the hpoa file format will be refactored in the new year
- update udp test with hgnc instead of entrez gene
-  Fix mmrrc whitespace issue
Test runs:
http://ci.monarchinitiative.org/job/build-mmrrc-ttl/40/
http://ci.monarchinitiative.org/job/build-hpoa-ttl/53/
http://ci.monarchinitiative.org/job/build-flybase-ttl/76/

Fixes for flybase, hpoa, mmrrc

---

dipper/sources/ZFIN.py

although I am a fan of terminated fields over separators they work best when they are visible
i.e. pipes  '|' 
it seems they made a sweep of the download directory and stripped the final tab from the files
who knows, maybe it will be back again next time

ZFIN  ditched trailing tabs

---

dipper/sources/OMIM.py
dipper/sources/Source.py

When checking response headers, make sure we are setting any request headers specified by the parser.  Fixes access issues with OMIM.

Send request headers when checking response headers

---

dipper/graph/RDFGraph.py
dipper/models/Dataset.py
dipper/sources/OMIM.py

We might want to know more about the sudden drop in descriptions.  
Bonus cleanup of unused function in RDFGraph  
Dataset was changed to use the graph identifier as the "name" of a named graph instead of the title which only happened when the graph type was not explicitly specified.  
This was problematic because although rdflib has no problem using the title as the graph name internally,it could fail when trying to export if the title included non URL safe characters such as space or other chars which need url encoding

OMIM adjustments

---

Makefile
dipper/models/Evidence.py
dipper/models/Model.py
dipper/sources/MGI.py
resources/sql/mgi/evidence.sql
resources/sql/mgi/voc_evidence_view.sql
tests/resources/mgi/evidence_view
tests/test_mgi.py
translationtable/global_terms.yaml

Updates the mgi db evidence query to include association metadata such as sex specificity - I wouldn't consider this evidence, but this is their representation.  For now I am hanging this off the association node.  See the unit test for an example input/output.
We are now getting back some other fields that may be useful, but are not added to the ingest in this PR:
Data Interpretation Center (eg IMPC)
external ref (eg UniProtKB:Q9JHI2-3 for Proteoform/Marker assoc)
Phenotyping Center (eg WTSI)
Resource Name (eg MGP)
Related ticket: https://github.com/monarch-initiative/dipper/issues/583

Add sex specific G2P qualifier from MGI

---

dipper/sources/Bgee.py

BGEE sends different formats when not specified `.zip` and `.gz` have been seen

try forcing the compression type #610 followup

---

dipper/models/Family.py
dipper/sources/GWASCatalog.py

should check if I added the extra `model =`  line elsewhere but if so, they will show up anyway.
I am liking just setting mandatory to false when the input is more variable

paste-o amd optional resolve  #610 followup

---

translationtable/go.yaml

I would prefer an ingest just used there lowercase ingest name as its tag
but `GeneOntology.py` uses `go` as its tag.
so for now, changing the local mapping file to suit

rename geneontology local tt file so it is found

---

dipper/graph/Graph.py
dipper/graph/RDFGraph.py
dipper/graph/StreamedGraph.py
dipper/models/assoc/Association.py
dipper/models/assoc/D2PAssoc.py

Trying to reduce the occurrence of rdf object as a literal when it should be a curie/IRI
previously rdf objects defaulted to literals, now if undeclared, 
an effort is made to determine if the object could be a literal or not

moving a check further up

---

dipper/sources/MMRRC.py
dipper/sources/Source.py
scripts/mysql2sqlite
translationtable/mmrc.yaml

fix bad data. MGI curie missing the 'I'  
however since I was in to find & fix that a bunch of other refactoring happened as well.
mmrrc
- table column headers conform to the new practice now
- logging reduced, just a summary at the end  when a symbol is missing an identifier  
- remove some of the scrubbing for issues not happening now/anymore  
- replace hard coded identifiers with translation table lookups
-  reduce using regexps  for plain string slices.
Source:
- eliminate the reuse/clobber of 'row' as both a list and a dict in a loop
- comments on vagueness of a very specific parser  (MySQL_XML dump)
- needs revisiting
scripts/mysql2sqlite
- script from GitHub to transform MySQL dumps into Sqlite syntax I use

MMRRC fix ++

---

dipper/sources/GeneOntology.py
dipper/sources/OMIM.py
scripts/ntriple2dot.awk

OMIM was built using the same curies for omim identifiers and Phenotypic Series identifiers
this PR corrects that.  closes #701
Movement towards codifying the expected incoming headers 
(as has happened across many ingests already)
is also captures in a pre functional state.
These column headers are used to detect/warn of incoming churn and  to 
mitigate code changes for simple column rearrangement/add/drop
(unless a dropped  column is explicitly required) 
and to preserve the source’s intent  for the data our code is acting on.

OMIM: adopt Phenotypic Series curie 

---

dipper/curie_map.yaml
dipper/sources/NCBIGene.py
dipper/sources/Source.py
tests/test_animalqtl.py
tests/test_source.py

increasing distinctions between when a variable is a bare identifier v.s. when it is qualified 
allowed an error when the current curie fell out of sync with the current bare identifier.
closes #704

NCBI gene  taxon assignment fix

---

dipper/sources/NCBIGene.py

increasing distinctions between when a variable is a bare identifier v.s. when it is qualified 
allowed an error when the current curie fell out of sync with the current bare identifier.
closes #704

avoid adding curie colon twice

---

dipper/sources/GeneOntology.py

Updated some GO annotation files. Should fix some errors in the current Dipper ingest. 
I've changed the domain to pull GO gene annotations from http://current.geneontology.org/annotations/ per Seth's suggestion. This current subdomain contains the "release" version of these files. These should be fairly stable.

Update GO gene annotation URLs

---

dipper/sources/HGNC.py
dipper/sources/Source.py
tests/test_hgnc.py
tests/test_hpoa.py
tests/test_kegg.py
tests/test_oma.py
tests/test_panther.py
tests/test_source.py

HGNC has several types which get a trailing '@' appended to the gene symbol.
the majority of these are  not propagates because they are of type "withdrawn" 
of the remaining 10, 6 are not propagated because they were of type 'region'
from the comments, the remaining four most likely were expected to be excluded as well
for having the '@' but have other types  ... RNA cluster which were not filtered.
I have changed the test from the type being `region` to if there is a trailing `@` on the symbol
which excludes the remaining few.
(note the items in the clusters/regions have their own HGNC ids that we keep)
-------------------
When centralizing the common test ids and converting the format to YAML 
some tests fell by the wayside and are now back to running.

HGNC @  and common test ids

---

dipper/sources/OMIM.py

bring back phenotypic series.
changing a test from not greater than one to exactly one earlier this year 
unnecessary caused a drop in the number of PhenotypicSeries to OMIM associations.
the solution is to remove the dependency altogether (including when test is greater than one)

OMIM phenotypic series inclusion

---

Jenkinsfile

This is another refactor of the jenkins pipeline that uses environment variables to enable single source runs and optionally write to /dev vs /ttl on data.monarch.
Down the line we may consider to put this pipeline into its own repo and make a multibranch pipeline, where each branch corresponds to a single source. See https://jenkins.io/doc/book/pipeline/multibranch/#creating-a-multibranch-pipeline
Example in jenkins:
https://ci.monarchinitiative.org/view/dipper/job/build-flybase-test/configure

Add environment variables for single source runs

---

dipper/sources/ZFIN.py

Removes testsuite code that resulted in a handful of source filepaths being overwritten in dipper-etl.py.  Our qc caught this via:
Genotype Phenotype
Danio rerio | 653 (-101276)
Variant Phenotype
Danio rerio | 8132 (-83923)
Variant Genotype
Danio rerio | 4 (-153358)

Remove testsuite from zfin

---

dipper/sources/StringDB.py

- do not trust tab file to have tab separated header
- do not trust `make string-test` to find out

String header check

---

Jenkinsfile

Our panther fetcher is not downloading complete files from the panther ftp (silently), this is a quick patch to use wget instead.

Use wget to fetch panther files

---

Jenkinsfile

Some of our sources utilize the OMIM dataset to determine if an OMIM id is a disease or a gene.  Running these all in parallel causes us to query OMIM at too frequently.

Run omim sources serially

---

dipper/sources/CTD.py
dipper/sources/KEGG.py

Per @cmungall 's request - removing the gene to disease parsers from kegg and CTD.  Closes #814

Comment out gene to disease parser for ctd and kegg

---

dipper/sources/MGI.py

Error results from this line in prb_strain_acc_view:
`06335		37	78775	1`
The code in MGI.py assumes the first column here is going to have a 'EM:' prefix, which it usually does. This 'EM:' prefix is substituted with ['EMMA:'](https://github.com/monarch-initiative/dipper/blob/e185cf24ecb5d2aa111bf19fa8822fc20444ed35/dipper/sources/MGI.py#L1729) and used as a strain_id later on.
The ingest fails when this first column above is used as strain_id, which is used as subject in a triple later on [here](https://github.com/monarch-initiative/dipper/blob/e185cf24ecb5d2aa111bf19fa8822fc20444ed35/dipper/sources/MGI.py#L1762), causing this:
```
ERROR:dipper.utils.CurieUtil:Not a properly formed curie: "06335"
ERROR:dipper.graph.RDFGraph:couldn't make URI for 06335
Traceback (most recent call last): …
```

Fix parse error causing MGI ingest to fail

---

dipper/sources/AnimalQTLdb.py
dipper/sources/FlyBase.py
dipper/sources/KEGG.py
dipper/sources/MMRRC.py

This PR fixes problems causing AnimaQTLdb, Flybase, and MMRRC ingests to fail.
* AnimalQTLdb:
* added column info to be consistent with how other ingests do row checking while ingesting files
* fixed ingest to recover when bad data is encountered in _process_qtls_genetic_location() - two records from source contain extra columns
* Flybase:
* fixed error while parsing fbrf_pmid_pmcid_doi_fb_.*.tsv.gz, caused by encoding not being set correctly (latin-1)
* MMRRC:
fixed two problems in parsing mmrrc_catalog_data.csv:
* one record from source contains extra columns, causing ingest to fail because of ValueError
* header was being parsed incorrectly, causing first two records to be silently ignored, because of change in format of header upstream at MMRRC

Fix parse errors animalqtldb flybase mmrrc

---

dipper/models/Dataset.py
dipper/models/Model.py
dipper/sources/Source.py
tests/test_dataset.py
tests/test_source_metadata.py

This PR alters the dataset summary, version, and distribution IRIs from:
```
https://archive.monarchinitiative.org/[source]
https://archive.monarchinitiative.org/[source]_[version]
https://archive.monarchinitiative.org/[source]_[version].[distribution file type]
```
To what Tom suggests:
```
https://archive.monarchinitiative.org/#[source]
https://archive.monarchinitiative.org/[version]/#[source]
https://archive.monarchinitiative.org/[version]/rdf/[source].[distribution type]
```
For example for RGD these IRIs will now be: 
```
https://archive.monarchinitiative.org/#rgd
https://archive.monarchinitiative.org/201908/#rgd
https://archive.monarchinitiative.org/201908/rdf/rgd.ttl
```
n.b. Dipper doesn't consider the CURIE versions of these IRIs (e.g. `MonarchArchive:/#rgd`) to be valid CURIEs, …

Modify dataset IRIs

---

dipper/sources/OMIMSource.py

Several weeks ago Monarch  offended OMIM by pulling a file too many times in too short a period and they implemented a quota on how many times we will be served.
To avoid running afoul of their quota in the future we now pull the file once cache it locally and ingests pull from that cache.

OMIM caching

---

.yamllint
Makefile
Pipfile
dipper/curie_map.yaml
requirements.txt

Have a single test for python virtual environment shared by all rules that use it.
Rename rules for clarity, consistency or to take advantage of being in a make environment.
Check for python virtual environment before all python unit tests
Reduce output when output is as expected  increase visual consistancy of test output.
Include `yamllint` requirement same as `pylint` requirement within virtual env
Move `.yamllint` config to the root dir.
Clean up `dipper/curie_map.yaml` and add linting it to the translation table rules
Run pylint in parallel to reduce testing time tax

Makefile refactor / clean up

---

dipper/sources/Panther.py

method is now instance method, but was decorated with `@staticmethod`

Fix bug in _clean_up_gene_id() caused by decorator @staticmethod

---

dipper/models/Dataset.py
tests/test_dataset.py

Per discussion with Kent, having the ontology declaration attached to a stable IRI is helpful for Scigraph reasons. 
I'm also adding a missing triple required by the HCLS spec, which was somehow missing

Move ontology declarations to summary level IRI, which is stable

---

dipper/sources/GeneOntology.py

In `zfin.gaf.gz`, very large entry in field 7 evidently breaks `csv`'s ability to parse with default field size limit. Increasing this fixes it

Fix for GO ingest

---

Jenkinsfile

Updated broken link to owltools to point to a working link for (and known version) of owltools. This link is broken for the time being because of power outages here at LBL. @kltm advised that the link we were using, even when it is working, is probably not a good choice, as it is likely to be volatile. 
(We could alternatively point to http://current.geneontology.org/bin/owltools, but we'd obviously be linking to an unknown version of owltools.)
Also, we possibly could/should be using robot instead of owltools here

Fix monarch owl build step in Dipper pipeline

---

Jenkinsfile
dipper/sources/Panther.py
resources/animalqtldb/README

I had wanted to make an incremental improvement in longest running timed ingest
but tests runs indicate that although more orthologs are processed in the same time  
many more orthologs are being found to process. 
spot checks (on sample run) indicate the new orthologs should have been there all along. 
missed genes seem to preferentially involve Ensembl identifiers. 
I expect this ingest will experience a wash for time (~16 hours) and output 300% of previous (including 100% of previous).
Will also note the additional genes/orthology/relations are not of a different kind.
Just a haphazard  sprinkle of more of the same.
6 hours 17 minutes  runtime and virtually identical output (9k fewer out of 52.7M)
things lost include URI incorrectly expressed as literals.
things gained (all 22 of them) …

Panther: refactor for efficency and correctness

---

Jenkinsfile
dipper/models/Dataset.py
tests/test_dataset.py

Two minor changes: 
- set `dcterms:created` using actual date instead of DATA_RELEASE_VERSION
- set DATA_RELEASE_VERSION in Jenkins using call to `date`

Set created on and data release version in metadata dynamically

---

dipper/curie_map.yaml
dipper/models/Dataset.py
dipper/sources/GeneOntology.py
tests/test_dataset.gv
tests/test_dataset.py
translationtable/generated/curiemap_prefix.txt

change our chosen prefix to match existing usage 
see:
http://prefix.cc/schema
extra: go edits 
- comments out fetching a file the ingest does not seem to use
- the file warns it is depreciated
- it's replacement is on DipperCache

prefix  'schemaorg:' to 'schema:' 

---

dipper/curie_map.yaml
dipper/sources/AnimalQTLdb.py
dipper/sources/MGI.py
dipper/sources/MMRRC.py
dipper/sources/NCBIGene.py
dipper/sources/Source.py
translationtable/generated/curiemap_prefix.txt

With Jenkins not failing loudly as often we can turn our attention to the stifled sobs coming from behind the wall of logs.
Here we make a pass at addressing the (down to) 100K ERROR messages dipper emits
with an eye first to reduce the greatest volume of less than tragic pronouncements.
Top of the list is "I can't find this curie prefix" which may be fixed by looking harder or
adding in what is missing.
There are other  errors having to do with column header name discrepancies
which can run from stray trailing spaces  to new underscore decorations to scarily different names which will need to be checked carefully after being run.
While looking for the sources of these reported errors there is the inevitable clean up as you go edits.

Jenkins ERROR log reductions

---

dipper/sources/FlyBase.py
dipper/sources/GeneOntology.py
dipper/utils/CurieUtil.py

new curie prefixes happened, 
either via fresh data ... or unblocking an existing pathway.
either way existing curie fixing mechanism seem to work,
the CurieUtil edit maybe premature but also seems not to break anything.
I am not a fan of gratuitously adopting new behaviour because it is shiny 
but stuck my nose in there (CU) because it is a hotspot in the panther ingest
so any bit helps.
That said addressing the added comment in an efficient manner 
is apt to swamp any benefit from the new string building format.

GO  rdf subjects as valid curies

---

Jenkinsfile
dipper-etl.py
dipper/sources/MGISlim.py
dipper/sources/Source.py
translationtable/mgi.yaml
translationtable/mgislim.yaml

MGISlim was inconsistently expressed with a hyphen and underscore where the ingest name convention is to use neither.
Source.resolve() has a use case where we only  expect to resolve as far as the local translation table where it should make less noise than when it is unexpected.
Since we expect some files to never be found in DipperCache mute the resulting 404s.
ICMP has many ways of expressing distinctions in mice origins we do not record.

MGISlim,  reduce expected "errors"

---

dipper/sources/ClinVar.py
dipper/sources/MGI.py

Created a list of ambiguous/unknown taxon terms that conflict with the local translation table (that default these terms to sequence alteration).
In ClinVar, replacing MedGene prefix with UMLS to better merge this data with mondo, per @cmungall , we only use these Ids in the absence of an OMIM id.
Test run for MGI: https://ci.monarchinitiative.org/job/build-mgi/3/console
Test run for ClinVar: https://ci.monarchinitiative.org/job/build-clinvar/
Fixes #906
Fixes #874

MGI: use Mus for unknown taxa, ClinVar: replace MedGen prefix with UMLS

---

dipper/utils/GraphUtils.py

Changed 
`https://purl.obolibrary.org/obo`
to 
`http://purl.obolibrary.org/obo`
The former apparently doesn't resolve, causing lots of ingests to fail

OBO url https -> http 

---

dipper/sources/Panther.py

Replaces triples that define genes as an owl:Class instead with rdf:type globaltt['gene']

panther - type genes as gene instead of owl:Class

---

dipper/curie_map.yaml
dipper/graph/RDFGraph.py
dipper/sources/GeneOntology.py
dipper/sources/Source.py
dipper/sources/UDP.py
scripts/ntriple2dot.awk
tests/test_udp.py

UDP (which I cannot run) got explicit MONARCH: curie prefix. Relying on default base prefix  results in a colon where we expect an underscore when processed with standard tools. (remember to fix tests)
Trying a run without duplicating metadata in the main graph, should eliminate whole classes of edge cases in post processing. 
Far fewer hardcoded curiemap  exceptions (for graphviz dot) theses days.
recently added try/except referenced non existent  .read() function 
spelling in comments type corrections

UDP  & misc

---

dipper/sources/AnimalQTLdb.py

The Gallus gallus file we're ingest still exists at NCBI, so it'd improve the metadata slightly to use this URL instead of the DipperCache URL.
Also added some comments in cases where we having to pull data files from DipperCache instead of NCBI

Revert Gallus gallus URL from Dipper Cache to NCBI URL

---

Jenkinsfile

Point bgee ingest in Jenkins at v14 to prevent current failure when trying to ingest 'current'

Point Bgee ingest at v14 

---

dipper/sources/Ensembl.py

'NCBI gene ID' col name changed to 'NCBI gene (formerly Entrezgene) ID'

Fix expected bmq_headers in Ensembl ingest

---

Jenkinsfile
dipper/sources/OMIM.py
dipper/sources/Source.py

increase the min time between api calls to avoid being throttled
Source.py  correct the logic when there is no file in dipper cache. was emitting inconsistant log message
Jenkind  minor cleanup, cerbose arg , remove redundant, consistant order

OMIM api call delay

---

requirements.txt

Upgrades rdflib back to version 5.0.0
We previously checked if a curie prefix was in our namespace via (I wrote this):
```if prefix not in self.namespace_manager.namespaces():```
Which in rdflib called
```
def namespaces(self):
for prefix, namespace in self.store.namespaces():
namespace = URIRef(namespace)
yield prefix, namespace
```
This check was applied for every triple added
The issue here being:
1. This never evaluates as true
2. This check is creating 3x len(namespace) URIRef objects every time we call addTriple, and then the perf hit of running graph.bind, in which the default is to override the namespace
In rdflib5 creating URIRef objects are slightly more expensive, which was exaggerated by this line.
I removed this in https://github.com/monarch-initiative/dipper/pull/746/commits/ …

Update rdflib to version 5

---

dipper/sources/OMIM.py

See #972, we should assign categories based on the omim type, not based on its position in a gene to disease association (which sometimes includes non diseases)

remove category from G2D

---

dipper/curie_map.yaml
dipper/models/Evidence.py
dipper/models/Model.py
dipper/sources/AnimalQTLdb.py
dipper/sources/EOM.py
dipper/sources/FlyBase.py
dipper/sources/GWASCatalog.py
dipper/sources/GeneOntology.py
dipper/sources/IMPC.py
dipper/sources/OMIA.py
dipper/sources/Orphanet.py
dipper/sources/WormBase.py
dipper/sources/ZFIN.py
translationtable/GLOBAL_TERMS.yaml
translationtable/generated/curiemap_prefix.txt

A pass across sources to mitigate inappropriate object literals.
- Model.py
RDF object curies with uncommon chars (such as '@') 
could be emitted as literals if not explicitly declared as non-literals. 
This P.R. expands the cases where we explicitly declare objects.
Add check for description not being empty
must be curie/URI.
- Orphanet
code comments were left for unintuitive cases 
and a stray line of comment was dropped
- Flybase
ftp url was assembled without a path separator (Dipper cache likely covers)
avoid empty species/taxon designations. (leads to taxon prefix as literal)
collect the scores of not-mapped "species" (which are most likely internal strain tags)
- Gwascatalog
Correct the guards on asserting up & down stream genes from a snp
previously missed asserting some that exist …

Orphanet via Model.py discourage CURIE/URI  objects as RDF literals  

---

dipper/models/Dataset.py
tests/test_dataset.py
translationtable/GLOBAL_TERMS.yaml

Currently the dataset descriptions created by `dipper` only have the class IRI for `dcat:Distribution` and not the property IRI of `dcat:distribution`.
This PR updates the `GLOBAL_TERMS.yaml` to include the property as part of the map and updates the code to use the property correctly.
Fun fact, I detected this using the `kgx` package while validating the results after running dipper-etl.py for ensembl. Here is an example of the error and dataset descriptor that isn't valid.
```
[ERROR][INVALID_EDGE_LABEL] https://archive.monarchinitiative.org/20200908/#ensembl-https://archive.monarchinitiative.org/20200908/rdf/ensembl.ttl - Edge label 'DistributionLevel' is not in snake_case form
```
```
@prefix biolink: <https://w3id.org/biolink/vocab/> .
@prefix dcat: <http://www.w3.org/ns/dcat#> . …
```

Disambiguate dcat:Distribution from dcat:distribution

---

dipper/models/GenomicFeature.py
dipper/models/Genotype.py
dipper/models/Model.py
dipper/models/Pathway.py
dipper/models/assoc/G2PAssoc.py
dipper/sources/AnimalQTLdb.py
dipper/sources/ClinVar.py
dipper/sources/Coriell.py
dipper/sources/Decipher.py
dipper/sources/IMPC.py
dipper/sources/KEGG.py
dipper/sources/MGI.py
dipper/sources/MMRRC.py
dipper/sources/MPD.py
dipper/sources/OMIA.py
dipper/sources/Source.py
dipper/sources/WormBase.py
dipper/sources/ZFIN.py

- try to have more bnode identifiers be predictable deterministic hashes
- wormbase got a refactor for column headers
- many misc refactos through out
embedding meaning in bnode identifiers as we have is a lost cause
hopefully no one relies on them.
We should be able to remove a bunch of processing intended to
keep cruft out of ids which never occur in a digest/hash hex-string.

Digest bnode ids &  refactor 

---

dipper/graph/RDFGraph.py
dipper/models/Genotype.py
dipper/models/Model.py
dipper/models/assoc/G2PAssoc.py
dipper/sources/MGI.py

bnode ids digested within the model classes needed an alternative 
to the digest function in Source.make_id()'  unless we change all the signatures to pass it.
zfin & mgi  run locally , expect others will as well

Adendum to PR #982   (Digest bnode ids & refactor)

---

dipper/curie_map.yaml
dipper/sources/GeneOntology.py
translationtable/animalqtldb.yaml

column 8 may use both pipe and comma as list delimiter.
Aparently, only pipe had been encountered thus  far.
update a skos base-uri

Go: fix list gaf list parsing

---

dipper/sources/MGI.py

Skip over phenotypes marked as normal in MGI, since we do not yet model normal phenotypes or negation

Skip normal phenotypes in MGI

---

translationtable/clinvar.yaml

clinvar has a new variant type called 'haplotype, single variant', translating it to our global term for 'haplotype'

add new variant type 'haplotype, single variant'

---

Jenkinsfile

See https://issues.jenkins.io/browse/JENKINS-66381
As of August 13 our username and password in the jenkins credentials store are no longer working.  Switching to SSH seems to resolve it.

Switch to SSH for private repo pull
